# Generated by Django 3.0 on 2020-04-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_date', models.DateTimeField(auto_now_add=True)),
                ('stage_order', models.FloatField(null=True)),
                ('stage_type', models.CharField(max_length=100)),
                ('water', models.FloatField(null=True)),
                ('rice', models.FloatField(null=True)),
                ('yeast', models.FloatField(null=True)),
                ('additive', models.FloatField(null=True)),
                ('description', models.TextField(default='설명을 입력하세요.', verbose_name='내용 ')),
            ],
        ),
        migrations.RemoveField(
            model_name='brew',
            name='name',
        ),
        migrations.AddField(
            model_name='brew',
            name='brew_description',
            field=models.TextField(default='설명을 입력하세요.', verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='brew',
            name='brew_name',
            field=models.CharField(default='untitled work', max_length=100),
        ),
        migrations.AlterField(
            model_name='brew',
            name='brew_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
